// Code generated by ogen, DO NOT EDIT.

package subscriptions

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetTotalCostSubscriptionsParams is parameters of GetTotalCostSubscriptions operation.
type GetTotalCostSubscriptionsParams struct {
	UserID      OptUUID   `json:",omitempty,omitzero"`
	ServiceName OptString `json:",omitempty,omitzero"`
	StartDate   string
	EndDate     string
}

func unpackGetTotalCostSubscriptionsParams(packed middleware.Parameters) (params GetTotalCostSubscriptionsParams) {
	{
		key := middleware.ParameterKey{
			Name: "user_id",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.UserID = v.(OptUUID)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "service_name",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ServiceName = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "start_date",
			In:   "query",
		}
		params.StartDate = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "end_date",
			In:   "query",
		}
		params.EndDate = packed[key].(string)
	}
	return params
}

func decodeGetTotalCostSubscriptionsParams(args [0]string, argsEscaped bool, r *http.Request) (params GetTotalCostSubscriptionsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: user_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "user_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotUserIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotUserIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.UserID.SetTo(paramsDotUserIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "user_id",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: service_name.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "service_name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotServiceNameVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotServiceNameVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ServiceName.SetTo(paramsDotServiceNameVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.ServiceName.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:    1,
							MinLengthSet: true,
							MaxLength:    255,
							MaxLengthSet: true,
							Email:        false,
							Hostname:     false,
							Regex:        nil,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "service_name",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: start_date.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "start_date",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.StartDate = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^\\d{2}-\\d{4}$"],
				}).Validate(string(params.StartDate)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "start_date",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: end_date.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "end_date",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.EndDate = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^\\d{2}-\\d{4}$"],
				}).Validate(string(params.EndDate)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "end_date",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// SubscriptionDeleteByIDParams is parameters of SubscriptionDeleteByID operation.
type SubscriptionDeleteByIDParams struct {
	// Уникальный идентификатор подписки.
	SubUUID string
}

func unpackSubscriptionDeleteByIDParams(packed middleware.Parameters) (params SubscriptionDeleteByIDParams) {
	{
		key := middleware.ParameterKey{
			Name: "sub_uuid",
			In:   "path",
		}
		params.SubUUID = packed[key].(string)
	}
	return params
}

func decodeSubscriptionDeleteByIDParams(args [1]string, argsEscaped bool, r *http.Request) (params SubscriptionDeleteByIDParams, _ error) {
	// Decode path: sub_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sub_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SubUUID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    1,
					MinLengthSet: true,
					MaxLength:    100,
					MaxLengthSet: true,
					Email:        false,
					Hostname:     false,
					Regex:        nil,
				}).Validate(string(params.SubUUID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sub_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SubscriptionGetByIDParams is parameters of SubscriptionGetByID operation.
type SubscriptionGetByIDParams struct {
	// Уникальный идентификатор подписки.
	SubUUID string
}

func unpackSubscriptionGetByIDParams(packed middleware.Parameters) (params SubscriptionGetByIDParams) {
	{
		key := middleware.ParameterKey{
			Name: "sub_uuid",
			In:   "path",
		}
		params.SubUUID = packed[key].(string)
	}
	return params
}

func decodeSubscriptionGetByIDParams(args [1]string, argsEscaped bool, r *http.Request) (params SubscriptionGetByIDParams, _ error) {
	// Decode path: sub_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sub_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SubUUID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    1,
					MinLengthSet: true,
					MaxLength:    100,
					MaxLengthSet: true,
					Email:        false,
					Hostname:     false,
					Regex:        nil,
				}).Validate(string(params.SubUUID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sub_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SubscriptionUpdateByIDParams is parameters of SubscriptionUpdateByID operation.
type SubscriptionUpdateByIDParams struct {
	// Уникальный идентификатор подписки.
	SubUUID string
}

func unpackSubscriptionUpdateByIDParams(packed middleware.Parameters) (params SubscriptionUpdateByIDParams) {
	{
		key := middleware.ParameterKey{
			Name: "sub_uuid",
			In:   "path",
		}
		params.SubUUID = packed[key].(string)
	}
	return params
}

func decodeSubscriptionUpdateByIDParams(args [1]string, argsEscaped bool, r *http.Request) (params SubscriptionUpdateByIDParams, _ error) {
	// Decode path: sub_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "sub_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.SubUUID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    1,
					MinLengthSet: true,
					MaxLength:    100,
					MaxLengthSet: true,
					Email:        false,
					Hostname:     false,
					Regex:        nil,
				}).Validate(string(params.SubUUID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sub_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
