// Code generated by ogen, DO NOT EDIT.

package subscriptions

// OperationName is the ogen operation name
type OperationName = string

const (
	GetSubscriptionOperation           OperationName = "GetSubscription"
	GetTotalCostSubscriptionsOperation OperationName = "GetTotalCostSubscriptions"
	SubscriptionCreateOperation        OperationName = "SubscriptionCreate"
	SubscriptionDeleteByIDOperation    OperationName = "SubscriptionDeleteByID"
	SubscriptionGetByIDOperation       OperationName = "SubscriptionGetByID"
	SubscriptionUpdateByIDOperation    OperationName = "SubscriptionUpdateByID"
)
