// Code generated by ogen, DO NOT EDIT.
package subscriptions

type GetSubscriptionRes interface {
	getSubscriptionRes()
}

type GetTotalCostSubscriptionsRes interface {
	getTotalCostSubscriptionsRes()
}

type SubscriptionCreateRes interface {
	subscriptionCreateRes()
}

type SubscriptionDeleteByIDRes interface {
	subscriptionDeleteByIDRes()
}

type SubscriptionGetByIDRes interface {
	subscriptionGetByIDRes()
}

type SubscriptionUpdateByIDRes interface {
	subscriptionUpdateByIDRes()
}
