// Code generated by ogen, DO NOT EDIT.

package subscriptions

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetSubscription implements GetSubscription operation.
	//
	// Получение списка списка отфильтрованных подписок.
	//
	// GET /api/v1/subscriptions
	GetSubscription(ctx context.Context, req OptGetSubscriptionsRequest) (GetSubscriptionRes, error)
	// GetTotalCostSubscriptions implements GetTotalCostSubscriptions operation.
	//
	// Производит подсчет стоимости всех подписок,
	// отобранных по фильтрам (user_id, service_name) и периодну от
	// (start_date до end_date).
	//
	// GET /api/v1/subscriptions/total-cost
	GetTotalCostSubscriptions(ctx context.Context, params GetTotalCostSubscriptionsParams) (GetTotalCostSubscriptionsRes, error)
	// SubscriptionCreate implements SubscriptionCreate operation.
	//
	// Создаёт новую подписку.
	//
	// POST /api/v1/subscriptions
	SubscriptionCreate(ctx context.Context, req *SubscriptionsReqDto) (SubscriptionCreateRes, error)
	// SubscriptionDeleteByID implements SubscriptionDeleteByID operation.
	//
	// Удаление данных о подписке .
	//
	// DELETE /api/v1/subscriptions/{sub_uuid}
	SubscriptionDeleteByID(ctx context.Context, params SubscriptionDeleteByIDParams) (SubscriptionDeleteByIDRes, error)
	// SubscriptionGetByID implements SubscriptionGetByID operation.
	//
	// Возвращает информацию о заказе.
	//
	// GET /api/v1/subscriptions/{sub_uuid}
	SubscriptionGetByID(ctx context.Context, params SubscriptionGetByIDParams) (SubscriptionGetByIDRes, error)
	// SubscriptionUpdateByID implements SubscriptionUpdateByID operation.
	//
	// Возвращает информацию о заказе.
	//
	// PUT /api/v1/subscriptions/{sub_uuid}
	SubscriptionUpdateByID(ctx context.Context, req *SubscriptionsReqDto, params SubscriptionUpdateByIDParams) (SubscriptionUpdateByIDRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
