// Code generated by ogen, DO NOT EDIT.

package subscriptions

import (
	"fmt"
	"time"

	"github.com/google/uuid"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/bad_request_error
type BadRequestError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val string) {
	s.Message = val
}

func (*BadRequestError) getSubscriptionRes()           {}
func (*BadRequestError) getTotalCostSubscriptionsRes() {}
func (*BadRequestError) subscriptionCreateRes()        {}
func (*BadRequestError) subscriptionGetByIDRes()       {}
func (*BadRequestError) subscriptionUpdateByIDRes()    {}

// Ref: #/components/schemas/create_subscription_response
type CreateSubscriptionResponse struct {
	// Уникальный идентификатор подписки.
	IDUUID OptUUID `json:"id_uuid"`
	// ID пользователя.
	UserID uuid.UUID `json:"user_id"`
}

// GetIDUUID returns the value of IDUUID.
func (s *CreateSubscriptionResponse) GetIDUUID() OptUUID {
	return s.IDUUID
}

// GetUserID returns the value of UserID.
func (s *CreateSubscriptionResponse) GetUserID() uuid.UUID {
	return s.UserID
}

// SetIDUUID sets the value of IDUUID.
func (s *CreateSubscriptionResponse) SetIDUUID(val OptUUID) {
	s.IDUUID = val
}

// SetUserID sets the value of UserID.
func (s *CreateSubscriptionResponse) SetUserID(val uuid.UUID) {
	s.UserID = val
}

func (*CreateSubscriptionResponse) subscriptionCreateRes() {}

// Ref: #/components/schemas/filters
type Filters struct {
	// ID пользователя.
	UserID OptString `json:"user_id"`
	// Название сервиса, предоставляющего подписку.
	ServiceName OptString `json:"service_name"`
}

// GetUserID returns the value of UserID.
func (s *Filters) GetUserID() OptString {
	return s.UserID
}

// GetServiceName returns the value of ServiceName.
func (s *Filters) GetServiceName() OptString {
	return s.ServiceName
}

// SetUserID sets the value of UserID.
func (s *Filters) SetUserID(val OptString) {
	s.UserID = val
}

// SetServiceName sets the value of ServiceName.
func (s *Filters) SetServiceName(val OptString) {
	s.ServiceName = val
}

// Ref: #/components/schemas/generic_error
type GenericError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val string) {
	s.Message = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

// Ref: #/components/schemas/get_subscription_response
type GetSubscriptionResponse struct {
	// Массив с подписками.
	Subscriptions []SubscriptionsRespDto `json:"subscriptions"`
	// Общее количество подписок в массиве.
	Total int64 `json:"total"`
}

// GetSubscriptions returns the value of Subscriptions.
func (s *GetSubscriptionResponse) GetSubscriptions() []SubscriptionsRespDto {
	return s.Subscriptions
}

// GetTotal returns the value of Total.
func (s *GetSubscriptionResponse) GetTotal() int64 {
	return s.Total
}

// SetSubscriptions sets the value of Subscriptions.
func (s *GetSubscriptionResponse) SetSubscriptions(val []SubscriptionsRespDto) {
	s.Subscriptions = val
}

// SetTotal sets the value of Total.
func (s *GetSubscriptionResponse) SetTotal(val int64) {
	s.Total = val
}

func (*GetSubscriptionResponse) getSubscriptionRes()     {}
func (*GetSubscriptionResponse) subscriptionGetByIDRes() {}

// Ref: #/components/schemas/get_totalcost_response
type GetTotalcostResponse struct {
	// Стомость всех выбранных подписок.
	TotalCost int64   `json:"total_cost"`
	Period    Period  `json:"period"`
	Filters   Filters `json:"filters"`
}

// GetTotalCost returns the value of TotalCost.
func (s *GetTotalcostResponse) GetTotalCost() int64 {
	return s.TotalCost
}

// GetPeriod returns the value of Period.
func (s *GetTotalcostResponse) GetPeriod() Period {
	return s.Period
}

// GetFilters returns the value of Filters.
func (s *GetTotalcostResponse) GetFilters() Filters {
	return s.Filters
}

// SetTotalCost sets the value of TotalCost.
func (s *GetTotalcostResponse) SetTotalCost(val int64) {
	s.TotalCost = val
}

// SetPeriod sets the value of Period.
func (s *GetTotalcostResponse) SetPeriod(val Period) {
	s.Period = val
}

// SetFilters sets the value of Filters.
func (s *GetTotalcostResponse) SetFilters(val Filters) {
	s.Filters = val
}

func (*GetTotalcostResponse) getTotalCostSubscriptionsRes() {}

// Ref: #/components/schemas/internal_server_error
type InternalServerError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerError) getSubscriptionRes()           {}
func (*InternalServerError) getTotalCostSubscriptionsRes() {}
func (*InternalServerError) subscriptionCreateRes()        {}
func (*InternalServerError) subscriptionDeleteByIDRes()    {}
func (*InternalServerError) subscriptionGetByIDRes()       {}
func (*InternalServerError) subscriptionUpdateByIDRes()    {}

// Ref: #/components/schemas/not_found_error
type NotFoundError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) subscriptionDeleteByIDRes() {}
func (*NotFoundError) subscriptionGetByIDRes()    {}
func (*NotFoundError) subscriptionUpdateByIDRes() {}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/period
type Period struct {
	// Дата начала подписки.
	StartDate string `json:"start_date"`
	// Дата окончании подписки.
	EndDate string `json:"end_date"`
}

// GetStartDate returns the value of StartDate.
func (s *Period) GetStartDate() string {
	return s.StartDate
}

// GetEndDate returns the value of EndDate.
func (s *Period) GetEndDate() string {
	return s.EndDate
}

// SetStartDate sets the value of StartDate.
func (s *Period) SetStartDate(val string) {
	s.StartDate = val
}

// SetEndDate sets the value of EndDate.
func (s *Period) SetEndDate(val string) {
	s.EndDate = val
}

// SubscriptionDeleteByIDNoContent is response for SubscriptionDeleteByID operation.
type SubscriptionDeleteByIDNoContent struct{}

func (*SubscriptionDeleteByIDNoContent) subscriptionDeleteByIDRes() {}

// Ref: #/components/schemas/subscriptions_req_dto
type SubscriptionsReqDto struct {
	// Название сервиса, предоставляющего подписку.
	ServiceName string `json:"service_name"`
	// Стоимость месячной подписки в рублях.
	Price int64 `json:"price"`
	// ID пользователя.
	UserID uuid.UUID `json:"user_id"`
	// Дата начала подписки.
	StartDate string `json:"start_date"`
	// Дата окончании подписки.
	EndDate OptString `json:"end_date"`
}

// GetServiceName returns the value of ServiceName.
func (s *SubscriptionsReqDto) GetServiceName() string {
	return s.ServiceName
}

// GetPrice returns the value of Price.
func (s *SubscriptionsReqDto) GetPrice() int64 {
	return s.Price
}

// GetUserID returns the value of UserID.
func (s *SubscriptionsReqDto) GetUserID() uuid.UUID {
	return s.UserID
}

// GetStartDate returns the value of StartDate.
func (s *SubscriptionsReqDto) GetStartDate() string {
	return s.StartDate
}

// GetEndDate returns the value of EndDate.
func (s *SubscriptionsReqDto) GetEndDate() OptString {
	return s.EndDate
}

// SetServiceName sets the value of ServiceName.
func (s *SubscriptionsReqDto) SetServiceName(val string) {
	s.ServiceName = val
}

// SetPrice sets the value of Price.
func (s *SubscriptionsReqDto) SetPrice(val int64) {
	s.Price = val
}

// SetUserID sets the value of UserID.
func (s *SubscriptionsReqDto) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetStartDate sets the value of StartDate.
func (s *SubscriptionsReqDto) SetStartDate(val string) {
	s.StartDate = val
}

// SetEndDate sets the value of EndDate.
func (s *SubscriptionsReqDto) SetEndDate(val OptString) {
	s.EndDate = val
}

// Ref: #/components/schemas/subscriptions_resp_dto
type SubscriptionsRespDto struct {
	// Уникальный номер подписки.
	ID uuid.UUID `json:"id"`
	// Название сервиса, предоставляющего подписку.
	ServiceName string `json:"service_name"`
	// Стоимость месячной подписки в рублях.
	Price int64 `json:"price"`
	// ID пользователя.
	UserID uuid.UUID `json:"user_id"`
	// Дата начала подписки.
	StartDate string `json:"start_date"`
	// Дата окончании подписки.
	EndDate OptString `json:"end_date"`
	// Дата создания подписки.
	CreatedAt time.Time `json:"created_at"`
	// Дата последнего обновления подписки.
	UpdatedAt time.Time `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *SubscriptionsRespDto) GetID() uuid.UUID {
	return s.ID
}

// GetServiceName returns the value of ServiceName.
func (s *SubscriptionsRespDto) GetServiceName() string {
	return s.ServiceName
}

// GetPrice returns the value of Price.
func (s *SubscriptionsRespDto) GetPrice() int64 {
	return s.Price
}

// GetUserID returns the value of UserID.
func (s *SubscriptionsRespDto) GetUserID() uuid.UUID {
	return s.UserID
}

// GetStartDate returns the value of StartDate.
func (s *SubscriptionsRespDto) GetStartDate() string {
	return s.StartDate
}

// GetEndDate returns the value of EndDate.
func (s *SubscriptionsRespDto) GetEndDate() OptString {
	return s.EndDate
}

// GetCreatedAt returns the value of CreatedAt.
func (s *SubscriptionsRespDto) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *SubscriptionsRespDto) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *SubscriptionsRespDto) SetID(val uuid.UUID) {
	s.ID = val
}

// SetServiceName sets the value of ServiceName.
func (s *SubscriptionsRespDto) SetServiceName(val string) {
	s.ServiceName = val
}

// SetPrice sets the value of Price.
func (s *SubscriptionsRespDto) SetPrice(val int64) {
	s.Price = val
}

// SetUserID sets the value of UserID.
func (s *SubscriptionsRespDto) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetStartDate sets the value of StartDate.
func (s *SubscriptionsRespDto) SetStartDate(val string) {
	s.StartDate = val
}

// SetEndDate sets the value of EndDate.
func (s *SubscriptionsRespDto) SetEndDate(val OptString) {
	s.EndDate = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *SubscriptionsRespDto) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *SubscriptionsRespDto) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*SubscriptionsRespDto) subscriptionUpdateByIDRes() {}

// Ref: #/components/schemas/validation_error
type ValidationError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ValidationError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ValidationError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ValidationError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ValidationError) SetMessage(val string) {
	s.Message = val
}

func (*ValidationError) getSubscriptionRes()           {}
func (*ValidationError) getTotalCostSubscriptionsRes() {}
func (*ValidationError) subscriptionCreateRes()        {}
