// Code generated by ogen, DO NOT EDIT.

package subscriptions

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetSubscription implements GetSubscription operation.
//
// Получение списка списка отфильтрованных подписок.
//
// GET /api/v1/subscriptions
func (UnimplementedHandler) GetSubscription(ctx context.Context, req OptGetSubscriptionsRequest) (r GetSubscriptionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTotalCostSubscriptions implements GetTotalCostSubscriptions operation.
//
// Производит подсчет стоимости всех подписок,
// отобранных по фильтрам (user_id, service_name) и периодну от
// (start_date до end_date).
//
// GET /api/v1/subscriptions/total-cost
func (UnimplementedHandler) GetTotalCostSubscriptions(ctx context.Context, params GetTotalCostSubscriptionsParams) (r GetTotalCostSubscriptionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SubscriptionCreate implements SubscriptionCreate operation.
//
// Создаёт новую подписку.
//
// POST /api/v1/subscriptions
func (UnimplementedHandler) SubscriptionCreate(ctx context.Context, req *SubscriptionsReqDto) (r SubscriptionCreateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SubscriptionDeleteByID implements SubscriptionDeleteByID operation.
//
// Удаление данных о подписке .
//
// DELETE /api/v1/subscriptions/{sub_uuid}
func (UnimplementedHandler) SubscriptionDeleteByID(ctx context.Context, params SubscriptionDeleteByIDParams) (r SubscriptionDeleteByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SubscriptionGetByID implements SubscriptionGetByID operation.
//
// Возвращает информацию о заказе.
//
// GET /api/v1/subscriptions/{sub_uuid}
func (UnimplementedHandler) SubscriptionGetByID(ctx context.Context, params SubscriptionGetByIDParams) (r SubscriptionGetByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SubscriptionUpdateByID implements SubscriptionUpdateByID operation.
//
// Возвращает информацию о заказе.
//
// PUT /api/v1/subscriptions/{sub_uuid}
func (UnimplementedHandler) SubscriptionUpdateByID(ctx context.Context, req *SubscriptionsReqDto, params SubscriptionUpdateByIDParams) (r SubscriptionUpdateByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
